
  global:
    - CC_TEST_REPORTER_ID=dbc0240c0ffa1db161c7ca6112c755da98251993789577d30220824a11b34a9d
language: ruby
rvm:
- 2.4.4
before_script: "bundle exec rails db:migrate"
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
deploy:
  provider: heroku
  api_key:
    secure: DonEoexKjjUqtgnpIpziFHLGGH4uKVgWMLJfXp5Ny8ltNzl3rEJ6jMjYl1vLeAZN6dk8h0nRQlC7wgNPO8kYxsqfm48sdtcu5CiD/7L2Fbn82GRawTM7jIVM+nM6mpio1pIioBrrN8drwCT3B1YvqfqszDLisIQsz40xi1YjGNMC/U3PtFwrT/nhoa9szOaNT53XmWZhBOfogscznk0Iha+70kXCzgmXtaaaG3GWX6xVbIWAQRh9KiJCiKok6lgOnbpCOClPNBdwyqaVTdD5bViI/iZH34tblTD0k9K2PzwniAwkwaJ1OfiZ1WCkBtJl9Jyjj9pHESPzyWBX832O8cR5gmV+dZiSwRjRQVP+2I8Bx1cS14orI9Nd5qKjiOarDq2YRyKfQYLfe4qh+UqytJjxqx9LCcZw6xENkr/9rp52/lfOuOAOmfb26JYYgJiWd9AKkJ38a0D3kCpDomztIMANCsC39dJDP72SlIzuqvyeM2AQvH5gFsWvrvgQDvTb4YgwpfMb2GlJxSx7fFWoQ58Uqdg6F+R3JYoRxCm5LHzk9BGx9jy5mqIvFkM+41AFeh7ChqGo/sDf4u6GW+U0FVivrzf43dR6MKkxllffi80S3QFtkxZ9HC8phGgfwnHPd5SviI2Fg4rAIzlm+XjBBcSF+UdoIVvvZS6+hTd0eeQ=
  app: gestpizza
  on:
    repo: larissakouete/Projet01
